cask_args appdir: '/Applications'
tap 'jjochen/cask'
tap 'vapor/homebrew-tap'
tap 'github/gh'
#tap 'homebrew/cask-drivers'


brew 'mas'

mas 'DaisyDisk', id: 411643860
mas 'DMG Architect', id: 426104753
mas 'Gemini', id: 463541543
mas 'Icon Set Creator', id: 939343785
mas 'Magnet', id: 441258766
mas 'Outbank', id: 1094255754
mas 'Paste JSON as Code • quicktype', id: 1330801220
mas 'Patterns', id: 429449079
mas 'Pastel', id: 413897608
mas 'Svgsus', id: 1106867065
mas 'Things', id: 904280696
mas 'WeatherPro', id: 966486618
#mas 'Xcode', id: 497799835


brew 'ansible'
brew 'ansible-lint'
brew 'astyle'
brew 'bash'
brew 'bash-completion'
brew 'carthage'
brew 'chruby'
brew 'circleci'
brew 'clang-format'
brew 'cmake'
brew 'cmatrix'
brew 'coreutils'
brew 'exa'
brew 'fasd'
brew 'findutils'
brew 'ffmpeg'
brew 'gh'
brew 'git'
brew 'git-lfs'
brew 'git-standup'
brew 'gnupg2'
#brew 'gpg-agent'
brew 'graphicsmagick'
brew 'htop'
brew 'imagemagick'
brew 'librsvg'
brew 'moreutils'
brew 'npm'
brew 'openssl'
brew 'potrace'
brew 'python'
brew 'rcm'
brew 'ruby-install'
brew 'ssh-copy-id'
brew 'subversion'
brew 'swi-prolog'
brew 'swiftformat'
brew 'swiftlint'
brew 'switchaudio-osx'
brew 'vapor'
brew 'vim', args: ['--override-system-vi']
brew 'wget'
brew 'xcproj'
brew 'xctool'
brew 'yamllint'
brew 'zsh'
brew 'zsh-autosuggestions'
brew 'zsh-completions'


cask '1password'
#cask '1password-cli'
cask 'airfoil'
cask 'alfred'
cask 'atom'
cask 'arduino'
cask 'base'
cask 'betterzipql'
cask 'bunqcommunity-bunq'
cask 'burn'
cask 'chrysalis'
cask 'db-browser-for-sqlite'
cask 'displaylink'
cask 'dropbox'
cask 'flycut'
cask 'github-desktop'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'handbrake'
cask 'hazel'
#cask 'hipchat'
#cask 'intelliscape-caffeine'
cask 'istat-menus'
cask 'iterm2'
cask 'kaleidoscope'
cask 'karabiner-elements'
cask 'kawa'
cask 'mactex'
cask 'macvim'
cask 'model01commander'
cask 'nucleo'
#cask 'paintcode'
cask 'pock'
cask 'postman'
cask 'provisioning'
cask 'provisionql'
cask 'qlcolorcode'
cask 'qlmarkdown'
#cask 'qlstephen'
cask 'qlswift'
cask 'quicklook-csv'
cask 'quicklook-json'
cask 'realm-browser'
#cask 'reflector'
cask 'renamer'
cask 'sequel-pro'
#cask 'sip'
cask 'sketch'
cask 'skim'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'spotify'
#cask 'stamp'
#cask 'steam'
#cask 'stride'
cask 'teamviewer'
cask 'textmate'
cask 'the-unarchiver'
#cask 'thingsmacsandboxhelper'
cask 'transmit'
cask 'vlc'
cask 'whatsapp'
cask 'xscope'
cask 'zoomus'


